services:
  postgres:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: json-file
      options:
        tag: docker-postgres

    networks:
      - db-net

volumes:
  db-data:
    name: db-data
  app-data:
    name: app-data

networks:
  db-net:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 10.20.31.0/24
  app-net:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 10.20.32.0/24
