services:
  postgres:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: journald
      options:
        tag: docker-postgres

  vaultwarden:
    image: vaultwarden/server:1.34.3
    restart: unless-stopped
    volumes:
      - vw-data:/data/
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      #- WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "81:80"
      #- "3012:3012"
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: journald
      options:
        tag: docker-vaultwarden

  nginx:
    image: nginx:1.27-bookworm-perl
    restart: unless-stopped
    volumes:
      - ${PWD}/docker/nginx.conf:/etc/nginx/conf.d/vaultwarden.conf:ro
      - ${PWD}/docker/crts/:/etc/nginx/crts/:ro
    ports:
      - "82:80"
      - "443:443"
    command: [nginx-debug, "-g", "daemon off;"]
    depends_on:
      vaultwarden:
        condition: service_started
    logging:
      driver: journald
      options:
        tag: docker-nginx

  pgbackups:
    image: prodrigestivill/postgres-backup-local:17
    user: 1001:1001
    restart: unless-stopped
    volumes:
      - ./docker/pgbackups:/backups
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_ON_START=TRUE
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=1
      - HEALTHCHECK_PORT=8080
    logging:
      driver: journald
      options:
        tag: docker/pgbackups

  nrpe-server:
    image: binfalse/nrpe-server:full
    restart: unless-stopped
    ports:
      - "5666:5666"
    volumes:
      - ./docker/nagios/certs/:/etc/nagios/certs/:ro
      - ./docker/nagios/cfg/:/etc/nagios/nrpe.d/:ro
      - ./docker/nagios/plugins/:/usr/lib/nagios/extra/:ro
      - /var:/monitor/var:ro
      - /usr:/monitor/usr:ro
      - /tmp:/monitor/tmp:ro
      - /home:/monitor/home:ro
      - /:/monitor/root:ro
    environment:
      SSL: "no"
      PORT: 5666
      ALLOWEDHOSTS: "10.223.111.51"
    logging:
      driver: journald
      options:
        tag: docker-nrpe

volumes:
  db-data:
    name: db-data
  vw-data:
    name: vw-data
