services:
  postgres:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_USER=app-user
      - POSTGRES_DB=app-db
volumes:
  db-data:
    name: db-data
