services:
  postgres:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    ports:
      - 5432:5432
    ### step 1: Volume persistence
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_USER=app_user
      - POSTGRES_DB=app_db
      # step 2: Hiding credentials from compose.yaml file
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- POSTGRES_USER=${POSTGRES_USER}
      #- POSTGRES_DB=${POSTGRES_DB}
    ### step 3: Adding healthcheck, tweak logging
    #healthcheck:
    #  test: ["CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5
    #logging:
    #  driver: json-file
    #  options:
    #    tag: docker-postgres
    #    max-size: "10m"
    #    max-file: "3"
### step 1: Volume persistence
volumes:
  db-data:
    name: db-data
