services:
  postgres:
    image: postgres:17.5-bookworm
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      #- POSTGRES_PASSWORD=pass1234
      #- POSTGRES_USER=app_user
      #- POSTGRES_DB=app_db
      # step 1: Hiding credentials from compose.yaml file
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
volumes:
  db-data:
    name: db-data
